---
- name: Install and configure Nginx with custom page
  hosts: webservers
  become: true

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom AWS index page
      copy:
        src: index-aws.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: inventory_hostname == "app_machine"

    - name: Copy custom Azure index page
      copy:
        src: index-azure.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      when: inventory_hostname == "tools_machine"

    - name: Reload Nginx to apply changes
      service:
        name: nginx
        state: reloaded

    - name: Verify Nginx is running
      shell: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Show Nginx running status
      debug:
        msg: "Nginx status: {{ nginx_status.stdout }}"
